(require 'package)
(push '("marmalade" . "http://marmalade-repo.org/packages/")
      package-archives )
(push '("melpa" . "http://melpa.milkbox.net/packages/")
      package-archives)
(push '("org" . "http://orgmode.org/elpa/")
      package-archives)
(push '("gnu" . "http://elpa.gnu.org/packages/")
      package-archives)
(package-initialize)
(defalias 'after 'with-eval-after-load)
(normal-erase-is-backspace-mode 1)
(require 'init-functions)
(require 'init-evil)
(provide 'init-local)
